stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw

  data_processing:
    cmd: python src/data/data_processing.py
    deps:
    - data/raw
    - src/data_processing.py
    params:
    - data_preprocessing
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    params:
    - feature_engineering
    outs:
    - data/interim
  model_building_1:
    cmd: python src/model/model_building_1.py
    deps:
    - data/interim
    - src/model_building_1.py
    params:
    - model_building_1
    outs:
    - data/processed_model
  model_building_2:
    cmd: python src/model/model_building_2.py
    deps:
    - data/processed_model
    - src/model_building_2.py
    params:
    - model_building_2
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/visualization/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    params:
    - model_evaluation
    metrics:
    - model_metrics.json
